#!/bin/bash

# Save trace setting
_XTRACE_NEUTRON_OVS=$(set +o | grep xtrace)
set +o xtrace

function neutron_plugin_create_nova_conf {
    :
}

function neutron_plugin_install_agent_packages {
    :
}

function is_neutron_ovs_base_plugin {
    return 1
}

function neutron_plugin_configure_debug_command {
    :
}

function neutron_plugin_configure_dhcp_agent {
    :
}

function neutron_plugin_configure_l3_agent {
    :
}

function neutron_plugin_configure_plugin_agent {
    AGENT_BINARY="neutron-lagopus-agent"
}

function neutron_plugin_setup_interface_driver {
    local conf_file=$1
    # TODO: Adds lagopus interface_driver
    iniset $conf_file DEFAULT interface_driver linuxbridge
}


function has_neutron_plugin_security_group {
    # 1 means False here
    return 0
}

function neutron_plugin_check_adv_test_requirements {
    is_service_enabled q-agt && is_service_enabled q-dhcp && return 0
}


function has_neutron_plugin_security_group {
    return 1
}

# Restore xtrace
$_XTRACE_NEUTRON_OVS
