#!/bin/bash

#    Licensed under the Apache License, Version 2.0 (the "License"); you may
#    not use this file except in compliance with the License. You may obtain
#    a copy of the License at
#
#         http://www.apache.org/licenses/LICENSE-2.0
#
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
#    WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
#    License for the specific language governing permissions and limitations
#    under the License.

# Save trace setting
_XTRACE_NEUTRON_LAGOPUS=$(set +o | grep xtrace)
set +o xtrace

function install_lagopus {
    local dir=${GITDIR['networking-lagopus']}
    
    git_clone $LAGOPUS_REPO $LAGOPUS_DIR $LAGOPUS_BRANCH
    cd $LAGOPUS_DIR
    ./configure --disable-dpdk
    make
    sudo make install
    sudo mkdir -p $LAGOPUS_CONF_DIR
    sudo cp $dir/devstack/$LAGOPUS_CONF $LAGOPUS_CONF_DIR/
    sudo sed -i -e "s/br-eth/$LAGOPUS_PHYSICAL_INTERFACE/g" $LAGOPUS_CONF_DIR/$LAGOPUS_CONF
}

function run_lagopus {
    sudo lagopus -C $LAGOPUS_CONF_DIR/$LAGOPUS_CONF -l $LAGOPUS_LOG
}

function stop_lagopus {
    sudo pkill -9 -f "lagopus -C $LAGOPUS_CONF_DIR/$LAGOPUS_CONF -l $LAGOPUS_LOG"
}

# Restore xtrace
$_XTRACE_NEUTRON_LAGOPUS
