#!/bin/bash

#    Licensed under the Apache License, Version 2.0 (the "License"); you may
#    not use this file except in compliance with the License. You may obtain
#    a copy of the License at
#
#         http://www.apache.org/licenses/LICENSE-2.0
#
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
#    WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
#    License for the specific language governing permissions and limitations
#    under the License.

LAGOPUS_VHOST_MODE=${LAGOPUS_VHOST_MODE:-True}
LAGOPUS_CONF_DIR=${LAGOPUS_CONF_DIR:-/usr/local/etc/lagopus}
LAGOPUS_CONF=${LAGOPUS_CONF:-lagopus.dsl}
LAGOPUS_LOG=${LAGOPUS_LOG:-/tmp/lagopus.log}
LAGOPUS_REPO=${LAGOPUS_REPO:-https://github.com/lagopus/lagopus.git}
LAGOPUS_BRANCH=${LAGOPUS_BRANCH:-master}
LAGOPUS_DIR=${LAGOPUS_DIR:-$DEST/lagopus}
LAGOPUS_INSTALL=${LAGOPUS_INSTALL:-False}
LAGOPUS_RUN=${LAGOPUS_RUN:-False}
LAGOPUS_PHYSICAL_INTERFACE=${LAGOPUS_PHYSICAL_INTERFACE:-eth1}
